/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/

#ifndef PTMASSEXPPDF
#define PTMASSEXPPDF

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"

class PtMassExpPdf : public RooAbsPdf {
public:
  PtMassExpPdf() {} ;
  PtMassExpPdf(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _B,
        RooAbsReal& _n1,
        RooAbsReal& _n2);
  PtMassExpPdf(const PtMassExpPdf& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new PtMassExpPdf(*this,newname); }
  inline virtual ~PtMassExpPdf() { }

protected:

  RooRealProxy x ;
  RooRealProxy B ;
  RooRealProxy n1 ;
  RooRealProxy n2 ;

  Double_t evaluate() const ;

private:

  ClassDef(PtMassExpPdf,1) // Your description goes here...
};

#endif
