input:
  run_list_file: /home/michele_pennisi/dimuon_HF_pp/MC_Analysis/Grid/general_run_information/LHC18p/run_list_part.txt
  alien_input_path: /alice/sim/2022/LHC22c1

output:
  output_dir: /home/michele_pennisi/dimuon_HF_pp/MC_Analysis/Grid/task_list/30_09_2022
  submitted_output_file: submitted
  terminated_output_file: terminated
  alien_output_path: .

data:
  run_list_file: /home/michele_pennisi/dimuon_HF_pp/MC_Analysis/Grid/general_run_information/LHC18p/run_list_part.txt
  macro_dir: Correct
  macro_to_run: new_ALICE_Muon_Analisys.C
  prefix_dir_fileout : "/home/michele_pennisi/dimuon_HF_pp/data/LHC18p/Hist_AOD"
  dir_fileout : "3_11_2022"

MC:
  run_list_file: /home/michele_pennisi/dimuon_HF_pp/MC_Analysis/Grid/general_run_information/LHC18p/run_list_part.txt
  macro_dir: /home/michele_pennisi/cernbox/HF_dimuons/mc_analysis/read_output
  macro_to_run: HistMCDimuonHF_lite.C
  input_dir: "30_09_2022"
  output_dir: /home/michele_pennisi/dimuon_HF_pp/data/LHC18p/Hist_MC/14_12_22
  prefix_filename: "MCDimuHFTree" 

copy:
  alien_output_path: /alice/cern.ch/user/m/mpennisi/HF_DimuAnalysis
  file_name: HF_MCDimuHFTree
  task_dir: /home/michele_pennisi/dimuon_HF_pp/MC_Analysis/Grid/task_list/30_09_2022
  terminated_output_file: terminated_HF_jobs.txt
  output_dir: /home/michele_pennisi/dimuon_HF_pp/Grid_Sim/HF/RunMCDimuHF/30_09_2022

merging_data:
  input_path: /home/michele_pennisi/dimuon_HF_pp/data/LHC18p/Hist_AOD/3_11_2022
  input_file_prefix: TreeResults
  output_path: /home/michele_pennisi/dimuon_HF_pp/data/LHC18p/Hist_AOD/3_11_2022
  output_file_prefix: TreeResults_merged

merging_MC:
  input_file: HistLite_HF_MCDimuHFTree
  output_path: /home/michele_pennisi/dimuon_HF_pp/data/LHC18p/Hist_MC/14_12_22
  output_file_prefix: HistLite_HF_MCDimuHFTree

# merging_MC:
#   input_file: HF_HFmixedAnalysis
#   output_path: /home/michele_pennisi/dimuon_HF_pp/data/LHC18p/Mixed_Analysis/12_10_22
#   output_file_prefix: HFmixedAnalysis_merged
