import ROOT as rt
def LoadStyle_canvas():
    rt.gStyle.SetImageScaling(3.)
    font = 42
    rt.gStyle.SetFrameBorderMode(0)
    rt.gStyle.SetFrameFillColor(0)
    rt.gStyle.SetCanvasBorderMode(0)
    rt.gStyle.SetPadBorderMode(0)
    rt.gStyle.SetPadColor(10)
    rt.gStyle.SetCanvasColor(10)
    rt.gStyle.SetTitleFillColor(10)
    rt.gStyle.SetTitleBorderSize(1)
    rt.gStyle.SetStatColor(10)
    rt.gStyle.SetStatBorderSize(1)
    rt.gStyle.SetLegendBorderSize(1)
    rt.gStyle.SetDrawBorder(0)
    rt.gStyle.SetTextFont(font)
    rt.gStyle.SetStatFontSize(0.05)
    rt.gStyle.SetStatX(0.97)
    rt.gStyle.SetStatY(0.98)
    rt.gStyle.SetStatH(0.03)
    rt.gStyle.SetStatW(0.3)
    rt.gStyle.SetTickLength(0.02, "y")
    rt.gStyle.SetEndErrorSize(3)
    rt.gStyle.SetLabelSize(0.04, "xyz")
    rt.gStyle.SetLabelFont(font, "xyz")
    rt.gStyle.SetLabelOffset(0.01, "xyz")
    rt.gStyle.SetTitleFont(font, "xyz")
    rt.gStyle.SetTitleOffset(0.9, "x")
    rt.gStyle.SetTitleOffset(1.02, "y")
    rt.gStyle.SetTitleSize(0.04, "xyz")
    rt.gStyle.SetMarkerSize(1.3)
    rt.gStyle.SetOptStat(0)
    rt.gStyle.SetEndErrorSize(0)
    rt.gStyle.SetCanvasPreferGL(rt.kTRUE)
    rt.gStyle.SetHatchesSpacing(0.5)

    canvas = rt.TCanvas("c", "c", 1600, 1200)
    canvas.cd()
    canvas.SetRightMargin(0.05)
    canvas.SetFillColor(0)
    canvas.SetBorderMode(0)
    canvas.SetBorderSize(0)
    canvas.SetTickx(1)
    canvas.SetTicky(1)
    canvas.SetLeftMargin(0.126)
    canvas.SetTopMargin(0.05)
    canvas.SetBottomMargin(0.12)
    canvas.SetFrameBorderMode(0)
    canvas.SetFrameBorderMode(0)

    return canvas


def main():
    fIn_drell=rt.TFile("sim/HFtest_Drell-Yan_2712_DefaultBR.root","READ")   
    fIn_drell.ls()

    h_PtDimu_DY=fIn_drell.Get("h_dimupt_OS_Z")
    h_PtDimu_DY.Rebin(10)    
    h_PtDimu_DY.Scale((1./5e+04)*3.506e-02,"width")
    h_PtDimu_DY.SetMarkerStyle(20)
    h_PtDimu_DY.SetMarkerColor(rt.kOrange+2)
    h_PtDimu_DY.SetLineColor(rt.kOrange+2)
    h_PtDimu_DY.SetLineWidth(3)

    fIn_HFsim = rt.TFile("~/cernbox/output_HF_dimuons/mc_analysis_output/Hist_fromSim/Version1/HF/HistLite_HF_MCDimuHFTree_merged.root", "READ")
    h_Nevents_HFsim = fIn_HFsim.Get("h_Nevents")
    nEvents_HFsim = h_Nevents_HFsim.GetBinContent(2)

    h_PtM_DimuHF_HFsim = fIn_HFsim.Get("DiMuon/M0/Rec_DQ_cut_match_LT/ULS/h_PtMDiMu_M0_Rec_DQ_cut_match_LT_ULS_fromHF")
    h_Pt_DimuHF_HFsim = h_PtM_DimuHF_HFsim.ProjectionX()
    h_Pt_DimuHF_HFsim.SetName("h_Pt_DimuHF_HFsim")

    h_M_DimuHF_HFsim = h_PtM_DimuHF_HFsim.ProjectionY()
    h_M_DimuHF_HFsim.SetName("h_M_DimuHF_HFsim")
    print("N dimu from HF %0.2f\n",h_M_DimuHF_HFsim.GetEntries())

    h_Pt_DimuHF_HFsim.Rebin(10)
    h_Pt_DimuHF_HFsim.Scale(56.42 / (216*nEvents_HFsim), "width")
    h_Pt_DimuHF_HFsim.SetMarkerStyle(24)
    h_Pt_DimuHF_HFsim.SetMarkerColor(rt.kBlue+2)
    h_Pt_DimuHF_HFsim.SetLineColor(rt.kBlue+2)
    h_Pt_DimuHF_HFsim.SetLineWidth(3)
    

    canvas_comparison=LoadStyle_canvas()
    canvas_comparison.cd()
    rt.gStyle.SetOptTitle(0)
    rt.gPad.SetLogy()
    h_Pt_DimuHF_HFsim.GetXaxis().SetTitle("#it{p}_{T} (GeV/#it{c})")
    h_Pt_DimuHF_HFsim.GetXaxis().SetTitleOffset(1.6)
    h_Pt_DimuHF_HFsim.GetXaxis().SetTitleSize(0.03)
    h_Pt_DimuHF_HFsim.GetXaxis().SetLabelSize(0.03)
    h_Pt_DimuHF_HFsim.GetYaxis().SetTitle("d#sigma_{#mu^{#plus}#mu^{#minus}}/d#it{p}_{T} (mb GeV^{-1} #it{c})")
    h_Pt_DimuHF_HFsim.GetYaxis().SetTitleOffset(1.6)
    h_Pt_DimuHF_HFsim.GetYaxis().SetTitleSize(0.035)
    h_Pt_DimuHF_HFsim.GetYaxis().SetLabelSize(0.035)
    h_Pt_DimuHF_HFsim.Draw("PE")
    h_PtDimu_DY.Draw("PESAME")

    Leged = rt.TLegend(0.18, 0.18, 0.325, 0.425, " ", "brNDC")
    

    Leged.AddEntry(h_Pt_DimuHF_HFsim, "#mu^{#plus}#mu^{#minus} #leftarrow HF", "EP")
    Leged.AddEntry(h_PtDimu_DY, "#mu^{#plus}#mu^{#minus} #leftarrow DY #times 10^{3}", "EP")

    Leged.SetBorderSize(0)
    Leged.SetFillColor(10)
    Leged.SetFillStyle(1)
    Leged.SetLineStyle(0)
    Leged.SetLineColor(0)
    Leged.SetTextFont(42)
    Leged.SetTextSize(0.035)
    Leged.Draw("SAME")
    rt.gPad.Update()
    canvas_comparison.SaveAs("DY_HF_comp.png")
    input()

main()